## 1.	Write a Python Program to Add Two Matrices?

In [3]:
def addmatrices(a,b):
    print(f"Inputs : {a}, {b}")
    if len(a) == len(b):
        res_matrix = []
        for i in range(len(a)):
            if len(a[i]) == len(b[i]):
                res_matrix.append([])
                for j in range(len(a[i])):
                    res_matrix[i].append(a[i][j]+b[i][j])
            else:
                print("Both matrices must contains same no. of rows and columns")
    else:
        print("Both matrices must contains same no. of rows and columns")
    print(f'Output : {res_matrix}')
    
addmatrices([[21,32,36],[45,53,24],[45,34,55]],[[96,85,71],[18,47,66],[77,36,65]])


Inputs : [[21, 32, 36], [45, 53, 24], [45, 34, 55]], [[96, 85, 71], [18, 47, 66], [77, 36, 65]]
Output : [[117, 117, 107], [63, 100, 90], [122, 70, 120]]


# OR

In [13]:
import numpy as np
a = [[21,32,36],[45,53,24],[45,34,55]]
b = [[96,85,71],[18,47,66],[77,36,65]]
c = []
c = np.add(a,b)
for r in c:
    print(r)

[117 117 107]
[ 63 100  90]
[122  70 120]


## 2.	Write a Python Program to Multiply Two Matrices?

In [11]:
import numpy as np
a = [[21,32,36],[45,53,24],[45,34,55]]
b = [[96,85,71],[18,47,66],[77,36,65]]
c = []
c = np.dot(a,b)
for r in c:
    print(r)

[5364 4585 5943]
[7122 7180 8253]
[9167 7403 9014]


## 3.	Write a Python Program to Transpose a Matrix?

In [14]:
a = [[21,32,36],[45,53,24],[45,34,55]]
t = []
t = np.transpose(a)
for i in t:
    print(i)

[21 45 45]
[32 53 34]
[36 24 55]


## 4.	Write a Python Program to Sort Words in Alphabetic Order?

In [20]:
def sorting():
    a = input("Enter a string : ")
    sort = sorted(a.split(' '))
    print(' '.join(sort))
sorting()

Enter a string : my name is chandan singh thakur
chandan is my name singh thakur


## 5.	Write a Python Program to Remove Punctuation From a String?

In [21]:
def removepunctuation():
    punctuations = "'!:;,.()[]{}-_<>?/\|@#$%^&*"
    in_string = input("Enter a string : ")
    out_string = " "
    for i in in_string:
        if i not in punctuations:
            out_string += i
    print(out_string)
    
removepunctuation()

Enter a string : my name is !chandan % & i love my
 my name is chandan   i love my
